#FROM nvcr.io/nvidia/deepstream:7.1-triton-multiarch
FROM nvcr.io/nvidia/deepstream:8.0-triton-multiarch

ARG CMAKE_VERSION_MAJOR=3
ARG CMAKE_VERSION_MINOR=25
ARG CMAKE_VERSION_PATCH=3

ARG EIGEN_VERSION_MAJOR=3
ARG EIGEN_VERSION_MINOR=4
ARG EIGEN_VERSION_PATCH=0

ARG OPENCV_VERSION_MAJOR=4
ARG OPENCV_VERSION_MINOR=12
ARG OPENCV_VERSION_PATCH=0

ARG PCL_VERSION_MAJOR=1
ARG PCL_VERSION_MINOR=15
ARG PCL_VERSION_PATCH=1

ARG PYBIND11_VERSION_MAJOR=2
ARG PYBIND11_VERSION_MINOR=13
ARG PYBIND11_VERSION_PATCH=0

ARG YAML_CPP_VERSION_MAJOR=0
ARG YAML_CPP_VERSION_MINOR=8
ARG YAML_CPP_VERSION_PATCH=0

ENV TZ=US/Pacific
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies
RUN apt-get update --fix-missing && apt-get install -y --no-install-recommends \
    # Python and development tools
    python3-pip \
    python3-dev \
    # Build tools and compilers
    build-essential \
    cmake \
    cmake-curses-gui \
    checkinstall \
    g++ \
    gcc \
    gfortran \
    # Version control and utilities
    git \
    vim \
    tmux \
    wget \
    curl \
    bzip2 \
    ca-certificates \
    gnupg \
    software-properties-common \
    # Graphics and GUI libraries
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgtk2.0-dev \
    libgtk2.0-dev \
    qtbase5-dev \
    # OpenGL / EGL libraries
    libgl1-mesa-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libglvnd-dev \
    # Math and science libraries
    libblas-dev \
    liblapack-dev \
    libatlas-base-dev \
    # Security and networking
    libssl-dev \
    libzmq3-dev \
    # Boost libraries
    libboost-filesystem-dev \
    libboost-date-time-dev \
    libboost-iostreams-dev \
    libboost-system-dev \
    libboost-program-options-dev \
    # Delete the all dev since it triggers to install MPI, which is incompatible with the specified PCL
    # libboost-all-dev \
    libboost-thread-dev \
    libboost-serialization-dev \
    libboost-chrono-dev \
    libboost-atomic-dev \
    libboost-regex-dev \
    # Point cloud and 3D processing
    libflann-dev \
    # Image and video processing
    libjpeg8-dev \
    libtiff5-dev \
    pkg-config \
    yasm \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libdc1394-dev \
    libxine2-dev \
    libv4l-dev \
    libtbb-dev \
    ffmpeg \
    # Audio/video codecs
    libfaac-dev \
    libmp3lame-dev \
    libtheora-dev \
    libvorbis-dev \
    libxvidcore-dev \
    libopencore-amrnb-dev \
    libopencore-amrwb-dev \
    x264 \
    v4l-utils \
    # Protocol buffers and logging
    libprotobuf-dev \
    protobuf-compiler \
    libgoogle-glog-dev \
    libgflags-dev \
    # Additional libraries
    libgphoto2-dev \
    libhdf5-dev \
    doxygen \
    proj-data \
    libproj-dev \
    libyaml-cpp-dev \
    libzmq3-dev \
    freeglut3-dev \
    && rm -rf /var/lib/apt/lists/*


ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/lib/python3.12/dist-packages/torch/lib:/usr/local/cuda/lib64:${LD_LIBRARY_PATH}

# Install Python packages directly with system Python to add additional conda env since docker should provide isolated environment
COPY requirements.txt /tmp/requirements.txt
RUN apt-get remove -y python3-blinker || true && \
    pip3 install --upgrade --ignore-installed --break-system-packages pip setuptools wheel && \
    pip3 install -r /tmp/requirements.txt \
    --index-url https://download.pytorch.org/whl/cu128 \
    --extra-index-url https://pypi.org/simple \
    --find-links https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.8.0_cu128.html \
    --break-system-packages && \
    # Install pyrender with --no-deps to bypass strict PyOpenGL 3.1.0 requirement (we use 3.1.10)
    pip3 install --no-deps --break-system-packages "pyrender==0.1.45" && \
    # Install PyTorch3D separately as it requires torch to be pre-installed and fails if torch has not been installed properlly
    pip3 install --no-build-isolation --break-system-packages "git+https://github.com/facebookresearch/pytorch3d.git@v0.7.9"

# Add local project to PYTHONPATH for development
ENV PYTHONPATH="${PYTHONPATH}:/workspace/BundleSDF"

# Install cmake
RUN cd / &&\
    wget http://www.cmake.org/files/v${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}/cmake-${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}.${CMAKE_VERSION_PATCH}.tar.gz &&\
    tar xf cmake-${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}.${CMAKE_VERSION_PATCH}.tar.gz &&\
    cd cmake-${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}.${CMAKE_VERSION_PATCH} &&\
    ./configure &&\
    make &&\
    make install


# Install Eigen
RUN cd / && \
    wget https://gitlab.com/libeigen/eigen/-/archive/${EIGEN_VERSION_MAJOR}.${EIGEN_VERSION_MINOR}.${EIGEN_VERSION_PATCH}/eigen-${EIGEN_VERSION_MAJOR}.${EIGEN_VERSION_MINOR}.${EIGEN_VERSION_PATCH}.tar.gz && \
    tar xf eigen-${EIGEN_VERSION_MAJOR}.${EIGEN_VERSION_MINOR}.${EIGEN_VERSION_PATCH}.tar.gz && \
    cd eigen-${EIGEN_VERSION_MAJOR}.${EIGEN_VERSION_MINOR}.${EIGEN_VERSION_PATCH} && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make install && \
    cd / && \
    rm -rf eigen-${EIGEN_VERSION_MAJOR}.${EIGEN_VERSION_MINOR}.${EIGEN_VERSION_PATCH}.tar.gz eigen-${EIGEN_VERSION_MAJOR}.${EIGEN_VERSION_MINOR}.${EIGEN_VERSION_PATCH}


# Install OpenCV
RUN cd / && \
    git clone --depth 1 --branch ${OPENCV_VERSION_MAJOR}.${OPENCV_VERSION_MINOR}.${OPENCV_VERSION_PATCH} https://github.com/opencv/opencv && \
    git clone --depth 1 --branch ${OPENCV_VERSION_MAJOR}.${OPENCV_VERSION_MINOR}.${OPENCV_VERSION_PATCH} https://github.com/opencv/opencv_contrib && \
    mkdir -p /opencv/build && \
    cd /opencv/build && \
    cmake ..  -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_CUDA_STUBS=OFF \
    -DBUILD_DOCS=OFF \
    -DWITH_MATLAB=OFF \
    -Dopencv_dnn_BUILD_TORCH_IMPORTE=OFF \
    -DCUDA_FAST_MATH=ON \
    -DMKL_WITH_OPENMP=ON \
    -DOPENCV_ENABLE_NONFREE=ON \
    -DWITH_OPENMP=ON \
    -DWITH_QT=ON \
    -DWITH_OPENEXR=ON \
    -DENABLE_PRECOMPILED_HEADERS=OFF \
    -DBUILD_opencv_cudacodec=OFF \
    -DINSTALL_PYTHON_EXAMPLES=OFF \
    -DWITH_TIFF=OFF \
    -DWITH_WEBP=OFF \
    -DWITH_FFMPEG=ON \
    -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
    -DCMAKE_CXX_FLAGS=-std=c++17 \
    -DENABLE_CXX11=OFF \
    -DBUILD_opencv_xfeatures2d=OFF \
    -DOPENCV_DNN_OPENCL=OFF \
    -DWITH_CUDA=ON \
    -DWITH_OPENCL=OFF \
    -DBUILD_opencv_wechat_qrcode=OFF \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_CXX_STANDARD_REQUIRED=ON \
    -DOPENCV_CUDA_OPTIONS_opencv_test_cudev=-std=c++17 \
    -DCUDA_ARCH_BIN="7.0 7.5 8.0 8.6 8.9 9.0 12.0" \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DINSTALL_PKGCONFIG=ON \
    -DOPENCV_GENERATE_PKGCONFIG=ON \
    -DPKG_CONFIG_PATH=/usr/local/lib/pkgconfig \
    -DINSTALL_PYTHON_EXAMPLES=OFF \
    -DINSTALL_C_EXAMPLES=OFF && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /opencv /opencv_contrib

# Install PCL
RUN cd / && \
    git clone --depth 1 --branch pcl-${PCL_VERSION_MAJOR}.${PCL_VERSION_MINOR}.${PCL_VERSION_PATCH} https://github.com/PointCloudLibrary/pcl && \
    mkdir -p /pcl/build && \
    cd /pcl/build && \
    cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_apps=OFF \
    -DBUILD_GPU=OFF \
    -DBUILD_CUDA=OFF \
    -DBUILD_examples=OFF \
    -DBUILD_global_tests=OFF \
    -DBUILD_simulation=OFF \
    -DCUDA_BUILD_EMULATION=OFF \
    -DCMAKE_CXX_FLAGS=-std=c++17 \
    -DPCL_ENABLE_SSE=ON \
    -DPCL_SHARED_LIBS=ON \
    -DWITH_VTK=OFF \
    -DPCL_ONLY_CORE_POINT_TYPES=ON \
    -DPCL_COMMON_WARNINGS=OFF && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /pcl

# Install Pybind11
RUN cd / && \
    git clone --depth 1 --branch v${PYBIND11_VERSION_MAJOR}.${PYBIND11_VERSION_MINOR}.${PYBIND11_VERSION_PATCH} https://github.com/pybind/pybind11 && \
    mkdir -p /pybind11/build && \
    cd /pybind11/build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /pybind11

# Install YAML-CPP
RUN cd / && \
    git clone --depth 1 --branch ${YAML_CPP_VERSION_MAJOR}.${YAML_CPP_VERSION_MINOR}.${YAML_CPP_VERSION_PATCH} https://github.com/jbeder/yaml-cpp && \
    mkdir -p /yaml-cpp/build && \
    cd /yaml-cpp/build && \
    cmake .. \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DBUILD_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DINSTALL_GTEST=OFF \
    -DYAML_CPP_BUILD_TESTS=OFF \
    -DYAML_BUILD_SHARED_LIBS=ON && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /yaml-cpp

# Install cppzmq
RUN cd / && \
    git clone --depth 1 https://github.com/zeromq/cppzmq && \
    mkdir -p /cppzmq/build && \
    cd /cppzmq/build && \
    cmake .. -DCPPZMQ_BUILD_TESTS=OFF && \
    make -j$(nproc) && \
    make install && \
    cd / && \
    rm -rf /cppzmq


# SHELL ["/bin/bash", "--login", "-c"]


ENV OPENCV_IO_ENABLE_OPENEXR=1
# Fix multiprocessing issues
ENV PYTHONUNBUFFERED=1
ENV OMP_NUM_THREADS=1

RUN imageio_download_bin freeimage
RUN apt-get update --fix-missing && \
    apt install -y rsync lbzip2 pigz zip p7zip-full p7zip-rar libxcb-cursor0

# WORKDIR /workspace/BundleSDF
